var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/u/[username]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zx5~my._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0w2vutu.js")
R.c("server/chunks/ssr/[root-of-the-server]__0m0m0pg._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01i7tsd._.js")
R.c("server/chunks/ssr/apps_website_0dib751._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_website__next-internal_server_app_u_[username]_page_actions_00z0c-g.js")
R.m(24837)
module.exports=R.m(24837).exports
