// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin-login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-login">> = Specific
  const handler = {} as typeof import("../../app/admin-login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/moderation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/moderation">> = Specific
  const handler = {} as typeof import("../../app/admin/moderation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/qa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/qa">> = Specific
  const handler = {} as typeof import("../../app/admin/qa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ads">> = Specific
  const handler = {} as typeof import("../../app/ads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/create">> = Specific
  const handler = {} as typeof import("../../app/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edit-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edit-profile">> = Specific
  const handler = {} as typeof import("../../app/edit-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/following/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/following">> = Specific
  const handler = {} as typeof import("../../app/following/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/post/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/post/[id]">> = Specific
  const handler = {} as typeof import("../../app/post/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reel/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reel/[id]">> = Specific
  const handler = {} as typeof import("../../app/reel/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/reels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reels">> = Specific
  const handler = {} as typeof import("../../app/reels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/safety/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/safety">> = Specific
  const handler = {} as typeof import("../../app/safety/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saved">> = Specific
  const handler = {} as typeof import("../../app/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/session-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/session-check">> = Specific
  const handler = {} as typeof import("../../app/session-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/story/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/story/[id]">> = Specific
  const handler = {} as typeof import("../../app/story/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/trash/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/trash">> = Specific
  const handler = {} as typeof import("../../app/trash/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/u/[username]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/u/[username]">> = Specific
  const handler = {} as typeof import("../../app/u/[username]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification">> = Specific
  const handler = {} as typeof import("../../app/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/media-library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media-library">> = Specific
  const handler = {} as typeof import("../../app/api/admin/media-library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/moderation/ads/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/moderation/ads/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/moderation/ads/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/moderation/reports/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/moderation/reports/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/moderation/reports/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/moderation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/moderation">> = Specific
  const handler = {} as typeof import("../../app/api/admin/moderation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/moderation/verification/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/moderation/verification/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/moderation/verification/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/overview">> = Specific
  const handler = {} as typeof import("../../app/api/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/qa/system/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/qa/system">> = Specific
  const handler = {} as typeof import("../../app/api/admin/qa/system/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reports/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reports/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session">> = Specific
  const handler = {} as typeof import("../../app/api/admin/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/archive">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/role">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/verify">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/verification/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/verification/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/admin/verification/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ads/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ads/[id]/status">> = Specific
  const handler = {} as typeof import("../../app/api/ads/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ads">> = Specific
  const handler = {} as typeof import("../../app/api/ads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/archive">> = Specific
  const handler = {} as typeof import("../../app/api/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/admin-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/admin-login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/admin-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats/message">> = Specific
  const handler = {} as typeof import("../../app/api/chats/message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/chats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chats">> = Specific
  const handler = {} as typeof import("../../app/api/chats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connections/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/health">> = Specific
  const handler = {} as typeof import("../../app/api/connections/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/create">> = Specific
  const handler = {} as typeof import("../../app/api/content/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/detail">> = Specific
  const handler = {} as typeof import("../../app/api/content/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/home-live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/home-live">> = Specific
  const handler = {} as typeof import("../../app/api/content/home-live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/home/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/home">> = Specific
  const handler = {} as typeof import("../../app/api/content/home/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/post">> = Specific
  const handler = {} as typeof import("../../app/api/content/post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/reel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/reel">> = Specific
  const handler = {} as typeof import("../../app/api/content/reel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/reels-live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/reels-live">> = Specific
  const handler = {} as typeof import("../../app/api/content/reels-live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/reels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/reels">> = Specific
  const handler = {} as typeof import("../../app/api/content/reels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/stories-live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/stories-live">> = Specific
  const handler = {} as typeof import("../../app/api/content/stories-live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/story/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/story">> = Specific
  const handler = {} as typeof import("../../app/api/content/story/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content/upload">> = Specific
  const handler = {} as typeof import("../../app/api/content/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creators/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creators/follow">> = Specific
  const handler = {} as typeof import("../../app/api/creators/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/creators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creators">> = Specific
  const handler = {} as typeof import("../../app/api/creators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed">> = Specific
  const handler = {} as typeof import("../../app/api/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow">> = Specific
  const handler = {} as typeof import("../../app/api/follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/follow/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow/status">> = Specific
  const handler = {} as typeof import("../../app/api/follow/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/follow/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/follow/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home/online-following/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/online-following">> = Specific
  const handler = {} as typeof import("../../app/api/home/online-following/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me">> = Specific
  const handler = {} as typeof import("../../app/api/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/messages/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/send">> = Specific
  const handler = {} as typeof import("../../app/api/messages/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/thread">> = Specific
  const handler = {} as typeof import("../../app/api/messages/thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/threads/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/threads/[id]/read">> = Specific
  const handler = {} as typeof import("../../app/api/messages/threads/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/threads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/threads/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/messages/threads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/threads/[id]/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/threads/[id]/send">> = Specific
  const handler = {} as typeof import("../../app/api/messages/threads/[id]/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/threads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/threads">> = Specific
  const handler = {} as typeof import("../../app/api/messages/threads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/messages/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/users">> = Specific
  const handler = {} as typeof import("../../app/api/messages/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notification-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification-summary">> = Specific
  const handler = {} as typeof import("../../app/api/notification-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/[id]/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[id]/read">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/[id]/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/list">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/mark-all-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-all-read">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/mark-all-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/mark-read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/mark-read">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/mark-read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/read-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/read-all">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/read-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/comment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/comment">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/comment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/detail">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/like">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/save">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/[id]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/[id]/share">> = Specific
  const handler = {} as typeof import("../../app/api/posts/[id]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts/delete">> = Specific
  const handler = {} as typeof import("../../app/api/posts/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/posts">> = Specific
  const handler = {} as typeof import("../../app/api/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-connections">> = Specific
  const handler = {} as typeof import("../../app/api/profile-connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-content/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-content">> = Specific
  const handler = {} as typeof import("../../app/api/profile-content/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-counts">> = Specific
  const handler = {} as typeof import("../../app/api/profile-counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-dynamic/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-dynamic">> = Specific
  const handler = {} as typeof import("../../app/api/profile-dynamic/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-follow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-follow">> = Specific
  const handler = {} as typeof import("../../app/api/profile-follow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile-settings">> = Specific
  const handler = {} as typeof import("../../app/api/profile-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/final/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/final">> = Specific
  const handler = {} as typeof import("../../app/api/profile/final/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/full/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/full">> = Specific
  const handler = {} as typeof import("../../app/api/profile/full/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/profile/update/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/update">> = Specific
  const handler = {} as typeof import("../../app/api/profile/update/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/[id]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/reels/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/[id]/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/[id]/detail">> = Specific
  const handler = {} as typeof import("../../app/api/reels/[id]/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/[id]/like">> = Specific
  const handler = {} as typeof import("../../app/api/reels/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/[id]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/[id]/share">> = Specific
  const handler = {} as typeof import("../../app/api/reels/[id]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/[id]/view">> = Specific
  const handler = {} as typeof import("../../app/api/reels/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels/delete">> = Specific
  const handler = {} as typeof import("../../app/api/reels/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reels">> = Specific
  const handler = {} as typeof import("../../app/api/reels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/safety/block/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safety/block">> = Specific
  const handler = {} as typeof import("../../app/api/safety/block/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/safety/blocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safety/blocks">> = Specific
  const handler = {} as typeof import("../../app/api/safety/blocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/safety/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safety/reports">> = Specific
  const handler = {} as typeof import("../../app/api/safety/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/safety/unblock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/safety/unblock">> = Specific
  const handler = {} as typeof import("../../app/api/safety/unblock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/saved-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saved-posts">> = Specific
  const handler = {} as typeof import("../../app/api/saved-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search-all">> = Specific
  const handler = {} as typeof import("../../app/api/search-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/all">> = Specific
  const handler = {} as typeof import("../../app/api/search/all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/secure-messages/archive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secure-messages/archive">> = Specific
  const handler = {} as typeof import("../../app/api/secure-messages/archive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/secure-messages/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secure-messages/conversations">> = Specific
  const handler = {} as typeof import("../../app/api/secure-messages/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/secure-messages/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secure-messages/send">> = Specific
  const handler = {} as typeof import("../../app/api/secure-messages/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/secure-messages/thread/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/secure-messages/thread">> = Specific
  const handler = {} as typeof import("../../app/api/secure-messages/thread/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/session/use-creator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/session/use-creator">> = Specific
  const handler = {} as typeof import("../../app/api/session/use-creator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/profile">> = Specific
  const handler = {} as typeof import("../../app/api/settings/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/comments/add/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/comments/add">> = Specific
  const handler = {} as typeof import("../../app/api/social/comments/add/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/comments/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/comments/list">> = Specific
  const handler = {} as typeof import("../../app/api/social/comments/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/like/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/like/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/social/like/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/save/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/save/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/social/save/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/share">> = Specific
  const handler = {} as typeof import("../../app/api/social/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/social/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/social/summary">> = Specific
  const handler = {} as typeof import("../../app/api/social/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/[id]/detail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]/detail">> = Specific
  const handler = {} as typeof import("../../app/api/stories/[id]/detail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/[id]/replies/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]/replies">> = Specific
  const handler = {} as typeof import("../../app/api/stories/[id]/replies/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/[id]/reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]/reply">> = Specific
  const handler = {} as typeof import("../../app/api/stories/[id]/reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/[id]/view">> = Specific
  const handler = {} as typeof import("../../app/api/stories/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories/delete">> = Specific
  const handler = {} as typeof import("../../app/api/stories/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/stories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stories">> = Specific
  const handler = {} as typeof import("../../app/api/stories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trash/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trash">> = Specific
  const handler = {} as typeof import("../../app/api/trash/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/list">> = Specific
  const handler = {} as typeof import("../../app/api/users/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/verification-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification-requests">> = Specific
  const handler = {} as typeof import("../../app/api/verification-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wallet/payout-request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet/payout-request">> = Specific
  const handler = {} as typeof import("../../app/api/wallet/payout-request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/wallet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wallet">> = Specific
  const handler = {} as typeof import("../../app/api/wallet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
