var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/edit-profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fjlo0p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_087vr8x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0m0m0pg._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01i7tsd._.js")
R.c("server/chunks/ssr/apps_website_0dib751._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/apps_website__next-internal_server_app_edit-profile_page_actions_0db8e0y.js")
R.m(97185)
module.exports=R.m(97185).exports
